// packages/svelte/src/lib/ConvexNudge.svelte
<script lang="ts">
  import {
    type NudgeOptions,
    getThemeColors,
    getPositionStyles,
    getAnimationStyles,
    getTextSize,
    getAnimationKeyframes,
    getGradientDirection,
    DEFAULT_OPTIONS,
    CONTAINER_STYLES,
    LINE_STYLES,
    LINK_STYLES,
    TEXT_STYLES,
    DISMISS_BUTTON_STYLES,
    getConvexUrl,
    getInlineSvgUrl
  } from '@convex-nudge/core';

  export let className = DEFAULT_OPTIONS.className;
  export let link: NudgeOptions['link'] = undefined;
  export let referralCode = DEFAULT_OPTIONS.referralCode;
  export let logoSize = DEFAULT_OPTIONS.logoSize;
  export let textSize = DEFAULT_OPTIONS.textSize;
  export let variant = DEFAULT_OPTIONS.variant;
  export let position = DEFAULT_OPTIONS.position;
  export let animation = DEFAULT_OPTIONS.animation;
  export let fixed = DEFAULT_OPTIONS.fixed;
  export let dismissible = DEFAULT_OPTIONS.dismissible;
  export let zIndex = DEFAULT_OPTIONS.zIndex;
  export let onDismiss: (() => void) | undefined = undefined;

  let isVisible = true;
  let isHovered = false;

  const colors = getThemeColors(variant);
  const positionStyles = getPositionStyles(position, fixed, zIndex);
  const animationStyles = getAnimationStyles(animation, position);
  const gradientDirection = getGradientDirection(position);

  const containerStyles = {
    ...CONTAINER_STYLES,
    ...positionStyles,
    ...animationStyles,
    opacity: isHovered ? 1 : colors.opacity,
    color: colors.text
  };

  const lineStyles = {
    ...LINE_STYLES,
    background: `linear-gradient(${gradientDirection}, transparent, ${colors.line}, transparent)`
  };

  const logoStyles = {
    height: `${logoSize}px`,
    width: `${logoSize}px`,
    opacity: 0.8
  };

  const textStyles = {
    ...TEXT_STYLES,
    fontSize: getTextSize(textSize)
  };

  const handleDismiss = () => {
    isVisible = false;
    onDismiss?.();
  };

  // Helper function to convert styles object to string
  const styleToString = (styles: Record<string, string | number>) => {
    return Object.entries(styles)
      .sort(([a], [b]) => a.localeCompare(b)) // Sort properties alphabetically
      .map(([key, value]) => `${key}: ${value}`)
      .join(';');
  };

  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();
</script>

{#if isVisible}
  <div class={className}>
    {@html `<style>${getAnimationKeyframes()}</style>`}
    <div style={styleToString(containerStyles)}>
      <div style={styleToString(lineStyles)} />
      <a
        href={getConvexUrl(link || referralCode)}
        target="_blank"
        rel="noopener noreferrer"
        style={styleToString(LINK_STYLES)}
        on:mouseenter={() => isHovered = true}
        on:mouseleave={() => isHovered = false}
      >
        <img
          src={getInlineSvgUrl()}
          alt="Convex"
          style={styleToString(logoStyles)}
        />
        <span style={styleToString(textStyles)}>
          Built with Convex
        </span>
      </a>
      <div style={styleToString(lineStyles)} />
      {#if dismissible}
        <button
          on:click={handleDismiss}
          style={styleToString(DISMISS_BUTTON_STYLES)}
          aria-label="Dismiss"
        >
          ×
        </button>
      {/if}
    </div>
  </div>
{/if}

// packages/vue/src/lib/ConvexNudge.vue
<!-- packages/vue/src/lib/ConvexNudge.vue -->
<script setup lang="ts">
import { ref } from 'vue';
import {
  type NudgeOptions,
  getThemeColors,
  getPositionStyles,
  getAnimationStyles,
  getTextSize,
  getAnimationKeyframes,
  CONTAINER_STYLES,
  LINE_STYLES,
  LINK_STYLES,
  TEXT_STYLES,
  DISMISS_BUTTON_STYLES,
  getConvexUrl,
  getInlineSvgUrl,
  DEFAULT_OPTIONS
} from '@convex-nudge/core';

const props = withDefaults(defineProps<{
  className?: string;
  link?: NudgeOptions['link'];
  referralCode?: string;
  logoSize?: number;
  textSize?: NudgeOptions['textSize'];
  variant?: NudgeOptions['variant'];
  position?: NudgeOptions['position'];
  animation?: NudgeOptions['animation'];
  fixed?: boolean;
  dismissible?: boolean;
  zIndex?: number;
}>(), {
  className: DEFAULT_OPTIONS.className,
  link: undefined,
  referralCode: DEFAULT_OPTIONS.referralCode,
  logoSize: DEFAULT_OPTIONS.logoSize,
  textSize: DEFAULT_OPTIONS.textSize,
  variant: DEFAULT_OPTIONS.variant,
  position: DEFAULT_OPTIONS.position,
  animation: DEFAULT_OPTIONS.animation,
  fixed: DEFAULT_OPTIONS.fixed,
  dismissible: DEFAULT_OPTIONS.dismissible,
  zIndex: DEFAULT_OPTIONS.zIndex
});

const emit = defineEmits<{
  (e: 'dismiss'): void;
}>();

const isVisible = ref(true);
const isHovered = ref(false);

const colors = getThemeColors(props.variant);
const positionStyles = getPositionStyles(props.position, props.fixed, props.zIndex);
const animationStyles = getAnimationStyles(props.animation, props.position);

const containerStyles = {
  ...CONTAINER_STYLES,
  ...positionStyles,
  ...animationStyles,
  opacity: isHovered.value ? 1 : colors.opacity,
  color: colors.text
};

const lineStyles = {
  ...LINE_STYLES,
  background: `linear-gradient(to right, transparent, ${colors.line}, transparent)`
};

const logoStyles = {
  height: `${props.logoSize}px`,
  width: `${props.logoSize}px`,
  opacity: 0.8
};

const textStyles = {
  ...TEXT_STYLES,
  fontSize: getTextSize(props.textSize)
};

const handleDismiss = () => {
  isVisible.value = false;
  emit('dismiss');
};
</script>

<template>
  <div v-if="isVisible" :class="className">
    <style v-html="getAnimationKeyframes()" />
    <div :style="containerStyles">
      <div :style="lineStyles" />
      <a
        :href="getConvexUrl(link || referralCode)"
        target="_blank"
        rel="noopener noreferrer"
        :style="LINK_STYLES"
        @mouseenter="isHovered = true"
        @mouseleave="isHovered = false"
      >
        <img
          :src="getInlineSvgUrl()"
          alt="Convex"
          :style="logoStyles"
        />
        <span :style="textStyles">Built with Convex</span>
      </a>
      <div :style="lineStyles" />
      <button
        v-if="dismissible"
        @click="handleDismiss"
        :style="DISMISS_BUTTON_STYLES"
        aria-label="Dismiss"
      >
        ×
      </button>
    </div>
  </div>
</template>

<style scoped>
.nudge-content {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
}

.message {
  margin: 0;
  font-size: 14px;
}

.message.info {
  color: #3b82f6;
}

.message.success {
  color: #22c55e;
}

.message.warning {
  color: #f59e0b;
}

.message.error {
  color: #ef4444;
}
</style>
